nelmio_api_doc:
    documentation:
        info:
            title: warehouse_api
            description: Тестовое задание.
            version: 0.0.0
        components:
            schemas:
                Credentials:
                    required:
                        - username
                        - password
                    properties:
                        username:
                            type: string
                        password:
                            type: string
                NewCategory:
                    required:
                        - name
                    properties:
                        name:
                            type: string
                    type: object
                Category:
                    type: object
                    allOf:
                        - $ref: '#/components/schemas/Category'
                        - required:
                              - id
                          properties:
                              id:
                                  type: integer
                              name:
                                  type: string
                              type: object
                          type: object
                NewProduct:
                    required:
                        - name
                        - price
                        - quantity
                        - category
                    properties:
                        name:
                            type: string
                        description:
                            type: string
                        price:
                            type: string
                        quantity:
                            type: string
                        category:
                            type: integer
                    type: object
                Product:
                    type: object
                    allOf:
                        - $ref: '#/components/schemas/Product'
                        - required:
                              - id
                          properties:
                              id:
                                  type: integer
                              name:
                                  type: string
                              description:
                                  type: string
                              price:
                                  type: number
                              quantity:
                                  type: number
                              category:
                                  $ref: '#/components/schemas/Category'
                          type: object
                ErrorModel:
                    required:
                        - code
                        - message
                    properties:
                        code:
                            type: integer
                            format: int32
                        message:
                            type: string
                    type: object
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
        paths:
            /api/login_check:
                post:
                    tags:
                        - Пользователи
                    summary: Получить токен.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                            example: test
                                        password:
                                            type: string
                                            example: test
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON.
                    security: [ ]

    areas: # to filter documented areas
        path_patterns:
#            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/api/product
            - ^/api/categor
            - ^/api/register