#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_register:
  path: /api/register
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  methods: [POST]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

overblog_graphql_endpoint:
  path: /api/graphql
  defaults:
    _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
    _format: "json"

overblog_graphql_batch_endpoint:
  path: /api/graphql/batch
  defaults:
    _controller: Overblog\GraphQLBundle\Controller\GraphController::batchEndpointAction
    _format: "json"

overblog_graphql_multiple_endpoint:
  path: /api/graphql/{schemaName}
  defaults:
    _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
    _format: "json"
  requirements:
    schemaName: '[^/]+'

overblog_graphql_batch_multiple_endpoint:
  path: /api/graphql/{schemaName}/batch
  defaults:
    _controller: Overblog\GraphQLBundle\Controller\GraphController::batchEndpointAction
    _format: "json"
  requirements:
    schemaName: '[^/]+'


overblog_graphiql_endpoint:
  path: /api/doc/graphiql
  defaults:
    _controller: Overblog\GraphiQLBundle\Controller\GraphiQLController::indexAction

overblog_graphiql_endpoint_multiple:
  path: /api/doc/graphiql/{schemaName}
  defaults:
    _controller: Overblog\GraphiQLBundle\Controller\GraphiQLController::indexAction

